package ct;
import java.util.HashMap;
import java.util.Map;

import org.junit.After;
import org.junit.Before;
// Generated by Selenium IDE
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
public class TestN0001Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  @Before
  public void setUp() {
	  System.setProperty("webdriver.chrome.driver", "exe/chromedriver.exe");
    driver = new ChromeDriver();
    try {
		Thread.sleep(5000);
	} catch (InterruptedException e) {

		e.printStackTrace();
	}

    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testN0001() {
    // Test name: test_N0.001
    // Step # | name | target | value
    // 1 | open | /businessBase/index.html |
    driver.get("http://localhost:8080/businessBase/index.html");
    driver.findElement(By.id("userId")).sendKeys("liushuang393");
    driver.findElement(By.id("password")).sendKeys("liushuang393");
    // 2 | setWindowSize | 1920x1080 |
    driver.manage().window().setSize(new Dimension(1920, 1080));
    // 3 | setSpeed | 500 |
    System.out.println("`set speed` is a no-op in code export, use `pause` instead");
    // 4 | click | id=login_sub |
    driver.findElement(By.id("login_sub")).click();
    // 5 | click | css=#left_tab2 > img |
    driver.findElement(By.cssSelector("#left_tab2 > img")).click();
    // 6 | click | id=dleft_tab1_8_span |
    driver.findElement(By.id("dleft_tab1_8_span")).click();
    // 7 | mouseOver | id=dleft_tab1_8_span |
    {
      WebElement element = driver.findElement(By.id("dleft_tab1_8_span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 8 | mouseOut | id=dleft_tab1_8_span |
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 9 | click | id=dleft_tab1_9_span |
    driver.findElement(By.id("dleft_tab1_9_span")).click();
    // 10 | selectFrame | index=0 |
    driver.switchTo().frame(0);
    // 11 | click | id=departmentId |
    driver.findElement(By.id("departmentId")).click();
    // 12 | type | id=departmentId | 123
    driver.findElement(By.id("departmentId")).sendKeys("123");
    // 13 | click | id=departmentName |
    driver.findElement(By.id("departmentName")).click();
    // 14 | type | id=departmentName | 部署名
    driver.findElement(By.id("departmentName")).sendKeys("部署名");
    // 15 | click | id=establishmentDay |
    driver.findElement(By.id("establishmentDay")).click();
    // 16 | click | linkText=1 |
    driver.findElement(By.linkText("1")).click();
    // 17 | click | name=searchBtn |
    driver.findElement(By.name("searchBtn")).click();
    // 18 | click | css=.text-center span |
    driver.findElement(By.cssSelector(".text-center span")).click();
    // 19 | click | id=establishmentDate |
    driver.findElement(By.id("establishmentDate")).click();
    // 20 | click | id=responsiblePerson |
    driver.findElement(By.id("responsiblePerson")).click();
    // 21 | type | id=responsiblePerson | 責任者2
    driver.findElement(By.id("responsiblePerson")).sendKeys("責任者2");
    // 22 | click | name=nextBtn |
    driver.findElement(By.name("nextBtn")).click();
    // 23 | click | name=updatBtn |
    driver.findElement(By.name("updatBtn")).click();
    // 24 | click | css=span |
    driver.findElement(By.cssSelector("span")).click();
    // 25 | click | css=.container > div:nth-child(2) |
    driver.findElement(By.cssSelector(".container > div:nth-child(2)")).click();
  }
}
